service: priority-tracker-api-js
app: priority-tracker
org: kavisherlock

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  useDotenv: true
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:BatchGetItem
      Resource:
        - "Fn::GetAtt": [CategoriesTable, Arn]
        - "Fn::GetAtt": [PrioritisedCategoriesTable, Arn]
        - "Fn::GetAtt": [ProjectsTable, Arn]
        - "Fn::GetAtt": [TasksTable, Arn]
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
      Resource: "arn:aws:dynamodb:*:*:table/*/index/*"

functions:
  - ${file(categories/functions.yml)}
  - ${file(categories/priorities/functions.yml)}
  - ${file(projects/functions.yml)}
  - ${file(tasks/functions.yml)}

resources:
  - ${file(categories/database.yml)}
  - ${file(categories/priorities/database.yml)}
  - ${file(projects/database.yml)}
  - ${file(tasks/database.yml)}
