Resources:
  TasksTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        -
          AttributeName: userId
          AttributeType: S
        -
          AttributeName: id
          AttributeType: S
        -
          AttributeName: project
          AttributeType: S
        -
          AttributeName: taskstatus
          AttributeType: S
      KeySchema:
        -
          AttributeName: userId
          KeyType: HASH
        -
          AttributeName: id
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      GlobalSecondaryIndexes:
        - IndexName: TaskStatusIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: taskstatus
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        - IndexName: TaskProjectIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
            - AttributeName: project
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
      TableName: ${self:provider.environment.DYNAMODB_TABLE}-Tasks
