create-task:
  handler: tasks/create.create
  events:
    - http:
        path: tasks
        method: post
        cors: true

get-tasks:
  handler: tasks/list.list
  events:
    - http:
        path: tasks
        method: get
        cors: true

get-active-tasks:
  handler: tasks/list.listActive
  events:
    - http:
        path: tasks/active
        method: get
        cors: true
        
get-category-tasks:
  handler: tasks/list.listCategory
  events:
    - http:
        path: categories/{categoryId}/tasks
        method: get
        cors: true

get-project-tasks:
  handler: tasks/list.listProject
  events:
    - http:
        path: projects/{projectId}/tasks
        method: get
        cors: true

get-task:
  handler: tasks/get.get
  events:
    - http:
        path: tasks/{id}
        method: get
        cors: true

update-task:
  handler: tasks/update.update
  events:
    - http:
        path: tasks/{id}
        method: put
        cors: true

delete-task:
  handler: tasks/delete.delete
  events:
    - http:
        path: tasks/{id}
        method: delete
        cors: true
