create-task:
  handler: tasks/create.create
  events:
    - http:
        path: tasks
        method: post
        cors: true

get-tasks:
  handler: tasks/list.list
  events:
    - http:
        path: tasks
        method: get
        cors: true

get-project-tasks:
  handler: tasks/list.listProject
  events:
    - http:
        path: projects/{projectId}/tasks
        method: get
        cors: true

get-task:
  handler: tasks/get.get
  events:
    - http:
        path: tasks/{id}
        method: get
        cors: true

update-task:
  handler: tasks/update.update
  events:
    - http:
        path: tasks/{id}
        method: put
        cors: true

update-task-status:
  handler: tasks/update.updateStatus
  events:
    - http:
        path: tasks/{id}/status
        method: put
        cors: true

delete-task:
  handler: tasks/delete.delete
  events:
    - http:
        path: tasks/{id}
        method: delete
        cors: true
